#!/bin/bash

##### Takes the txt file with the SRA ids or a single SRA id as the argument.
##### A text file only containing the SRA ids can be obtained from the NCBI website

set -e ## Exit if problems arise
#set -x ## For debugging

clear && echo "SRA scraper "
echo "A non interactive tool to download the Taxonomic data from the NCBI SRA database"
source functions.sh
while getopts "f:hi:" opt;do
	case "$opt" in
		f) [ -f "$OPTARG" ] && input_file="$OPTARG" && from_file ;;
		h) helpsra ;;
		i) id="$OPTARG" && id_search ;;
		\?) echo "Not a valid option" ;;
	esac
done

exit
