#!/bin/bash

##### Takes the txt file with the SRA ids or a single SRA id as the argument.
##### A text file only containing the SRA ids can be obtained from the NCBI website

set -e ## Exit if problems arise
#set -x ## For debugging
## Edit this variable if there is a change to the NCBI url structure
url="https://trace.ncbi.nlm.nih.gov/Traces/sra/?run="

clear && echo "SRA scraper "
echo "A non interactive tool to download the Taxonomic data from the NCBI SRA database"

## functions
from_file(){
	dos2unix "$input_file" # To remove '$':'/r' which is annoying
	readarray -t line < "$input_file"
	for sra in "${line[@]}"; do
		wget -q -O - "$url$sra" | grep "\"name\":" | sed 's_var\ oTaxAnalysisData\ =\ _\ _' | sed '$ s_}},\ _}]_' | sed 's_\"d\":{__' | sed 's_}},_},_' > "$sra".json ## wget  results get grepped with the keyword name inside quotes which is present in all lines of the data
  ## -q tag quiet and clean terminal result -O - to send the output to STDOUT
  ## sed to clean the data grepped
	done
	echo "DONE"
}
loading(){ ### not working ###
pid=$!
text=$1
while kill -0 $pid 2>/dev/null
do
  echo -ne "$text .\r"
  sleep 0.5
  echo -ne "$text ..\r"
  sleep 0.5
  echo -ne "$text ...\r"
  sleep 0.5
  echo -ne "\r\033[K"
  echo -ne "$text\r"
  sleep 0.5
done
## A function to display loading dots purely decorative
}
helpsra(){
echo
echo "[USAGE] scrape -f [FILENAME] or -i [SRA id]"
echo "scrape -h to print this help"
echo
echo "The script takes two types of arguments, A file containing the SRA ids for batch processing or a single SRA id"
echo "The file should contain only one SRA id per line."
echo "Such a file can be obtained from the NCBI website through Download > File > Accession number"
}

id_search(){
	wget -q -O - "$url$id" | grep "\"name\":" | sed 's_var\ oTaxAnalysisData\ =_\ _' | sed '$ s_}},\ _}]_' | sed 's_\"d\":{__' | sed 's_}},_},_'  > $1.json ## adding the file extension gives a better looking result
    echo "DONE"
}


while getopts "f:i:h" opt; do
	case "$opt" in
		f) [ -f "$OPTARG" ] && input_file="$OPTARG" && from_file;;
		i) id="$OPTARG" && id_search ;;
		h) helpsra ;;
		\?) echo "Invalid option";;
	esac
done

exit
